import './global.css';

export const metadata = {
  title: 'Welcome to web-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" style={{ colorScheme: 'dark' }}>
      <body>{children}</body>
    </html>
  );
}
