name: PR Checker

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true # this enables DTE
  NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3 # expected number of agents
  NX_BRANCH: ${{ github.event.number || github.ref_name }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  checker:
    name: Checker
    runs-on: ubuntu-latest
    steps:
      - name: Echo Env
        run: echo $NX_CLOUD_ACCESS_TOKEN
