name: PR Checker

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checker:
    name: Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: yarn install --frozen-lockfile

      - run: npx nx format:check
      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t tsc --parallel=3
      - run: npx nx affected -t test --parallel=3
